### ISSUE TITLE
dynamic

### ISSUE THREAD

**Issue by ddkwork** [PaulWaldo/fyne-headertable#1]
hello you，how to dynamic add row？

**Comment by PaulWaldo** [comment]
Hi @ddkwork, try adding the new item to your bindings and refreshing the component.  Here is a quick hack of the `plainheader` sample where this new row is added.

```go
	go func() {
		for range time.Tick(50 * time.Millisecond) {
			// Pick a random animal and adjust the Weight randomly
			// row := rand.Intn(len(animals))
			// newWeight := fmt.Sprintf("%d", rand.Intn(100))
			// animals[row].Weight = newWeight

			// Dynamically add another row
			animals = append(animals, Animal{Name: "XXX", Type: "dynamic", Color: "green", Weight: "200"})
			myTableOpts.Bindings = append(myTableOpts.Bindings, binding.BindStruct(&animals[len(animals)-1]))
			ht.Refresh()
			break
		}
```

**Comment by ddkwork** [comment]
Thx,i will try

**Comment by ddkwork** [comment]
> Hi @ddkwork, try adding the new item to your bindings and refreshing the component.  Here is a quick hack of the `plainheader` sample where this new row is added.
> 
> ```go
> 	go func() {
> 		for range time.Tick(50 * time.Millisecond) {
> 			// Pick a random animal and adjust the Weight randomly
> 			// row := rand.Intn(len(animals))
> 			// newWeight := fmt.Sprintf("%d", rand.Intn(100))
> 			// animals[row].Weight = newWeight
> 
> 			// Dynamically add another row
> 			animals = append(animals, Animal{Name: "XXX", Type: "dynamic", Color: "green", Weight: "200"})
> 			myTableOpts.Bindings = append(myTableOpts.Bindings, binding.BindStruct(&animals[len(animals)-1]))
> 			ht.Refresh()
> 			break
> 		}
> ```

I tested add  5000-10000 rows every 1 second with dynamic , it vert sloywly.

**Comment by PaulWaldo** [comment]
@ddkwork can you show a simple example of this behavior (code)?

**Comment by ddkwork** [comment]
> @ddkwork can you show a simple example of this behavior (code)?

Wait me, i can not use windows now.

**Comment by PaulWaldo** [comment]
@ddkwork I'm assuming the problem you are describing is a crash when scrolling.  The problem is that you declare there will be 1000 rows, but create them very slowly, causing a failure in accessing uncreated rows.  Try this variation using `append`
```go
package main

import (
	"fmt"
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/data/binding"
	"github.com/PaulWaldo/fyne-headertable/headertable"
	"github.com/PaulWaldo/fyne-headertable/headertable/cmd/data"
)

func main() {
	var bindings []binding.Struct
	var Transactions []data.Transaction
	go func() {
		time.Sleep(time.Second)
		for i := 0; i < 1000; i++ {
			Transactions = append(Transactions,
				data.Transaction{
					Payee: "Grocery Store", Amount: -154.96,
					Memo: "Food for party that I hosted " + fmt.Sprint(i),
					Date: time.Now().Add(-5 * time.Hour * 24),
				})
			time.Sleep(time.Second)
			bindings = append(bindings, binding.BindStruct(&Transactions[i]))
			data.TableOpts.Bindings = bindings
		}
	}()
	a := app.New()
	w := a.NewWindow("Header Table Test")
	w.Resize(fyne.NewSize(600, 300))
	ht := headertable.NewSortingHeaderTable(&data.TableOpts)
	w.SetContent(container.NewMax(ht))
	w.CenterOnScreen()
	w.ShowAndRun()
}
```

**Comment by ddkwork** [comment]
> @ddkwork I'm assuming the problem you are describing is a crash when scrolling.  The problem is that you declare there will be 1000 rows, but create them very slowly, causing a failure in accessing uncreated rows.  Try this variation using `append`
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"time"
> 
> 	"fyne.io/fyne/v2"
> 	"fyne.io/fyne/v2/app"
> 	"fyne.io/fyne/v2/container"
> 	"fyne.io/fyne/v2/data/binding"
> 	"github.com/PaulWaldo/fyne-headertable/headertable"
> 	"github.com/PaulWaldo/fyne-headertable/headertable/cmd/data"
> )
> 
> func main() {
> 	var bindings []binding.Struct
> 	var Transactions []data.Transaction
> 	go func() {
> 		time.Sleep(time.Second)
> 		for i := 0; i < 1000; i++ {
> 			Transactions = append(Transactions,
> 				data.Transaction{
> 					Payee: "Grocery Store", Amount: -154.96,
> 					Memo: "Food for party that I hosted " + fmt.Sprint(i),
> 					Date: time.Now().Add(-5 * time.Hour * 24),
> 				})
> 			time.Sleep(time.Second)
> 			bindings = append(bindings, binding.BindStruct(&Transactions[i]))
> 			data.TableOpts.Bindings = bindings
> 		}
> 	}()
> 	a := app.New()
> 	w := a.NewWindow("Header Table Test")
> 	w.Resize(fyne.NewSize(600, 300))
> 	ht := headertable.NewSortingHeaderTable(&data.TableOpts)
> 	w.SetContent(container.NewMax(ht))
> 	w.CenterOnScreen()
> 	w.ShowAndRun()
> }
> ```

It's still slow, when quickly and dynamically adding rows and selecting them. For example, in the scene of charles's package-grabbing tool, colleagues who add rows select rows by mouse, and other controls take out the contents of rows. In short, the event of selecting rows in the process of adding rows becomes very stuck. I don't know if it's a design problem of fyne. I tried several other ui libraries and the situation is better than fyne's.

**Comment by ddkwork** [comment]
you can try this， its so fast.

https://github.com/richardwilkes/unison

**Comment by PaulWaldo** [comment]
I'm not sure I understand.  The code you are using is slow by design; there is 1000 seconds of delay built in with `time.Sleep(time.Second)`

**Comment by ddkwork** [comment]
> I'm not sure I understand. The code you are using is slow by design; there is 1000 seconds of delay built in with time.Sleep(time.Second)

No, staying for 1 second is just to simulate dynamically adding rows. I mean that when each row is selected, it becomes stuck, for example, from the first row of mouse to the 50th row in turn. At this time, the onselect event is very stuck.

**Comment by ddkwork** [comment]
Imagine the fact-refreshing scenario of Windows task management. Combined with this example, one process is created every second to simulate the user running the app, and the information of each app process is refreshed to the task manager. . . If you can't reproduce the performance problem of this form control, I think I should upload a video to describe it.

**Comment by ddkwork** [comment]
After each row is added, the scroll bar automatically scrolls to the bottom.

**Comment by ddkwork** [comment]
After each row is added, the scroll bar should automatically scroll to the bottom.

**Comment by PaulWaldo** [comment]
Closed for inactivity

**Comment by PaulWaldo** [comment]
I'm not sure I understand. What should I test?

**Comment by ddkwork** [comment]
> I'm not sure I understand. What should I test?

test table widget
